---
#----------- Package Information ------------#
name: parkirin
description: "A solution for your everyday Parking!"

#----------- Publishing Settings ------------#
publish_to: "none" # Remove this line if you wish to publish to pub.dev

#----------- Versioning Information ------------#
version: 1.0.0+1

#----------- Environment Settings ------------#
environment:
  sdk: ^3.5.3

#----------- Dependencies ------------#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rive: ^0.13.14
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2

#----------- Dev Dependencies ------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


#----------- Flutter Settings ------------#
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
